frr version 9.1
frr defaults datacenter
hostname spine1
log syslog informational
!
interface lo
 ip address 10.255.0.1/32
!
interface eth1
 ip address 10.0.0.0/31
 description to-tor1
!
interface eth2
 ip address 10.0.0.2/31
 description to-tor2
!
router bgp 65000
 bgp router-id 10.255.0.1
 bgp bestpath as-path multipath-relax
 !
 neighbor 10.0.0.1 remote-as 65001
 neighbor 10.0.0.1 description tor1
 neighbor 10.0.0.3 remote-as 65002
 neighbor 10.0.0.3 description tor2
 !
 address-family ipv4 unicast
  network 10.255.0.1/32
  neighbor 10.0.0.1 activate
  neighbor 10.0.0.3 activate
 exit-address-family
!
line vty
!
