frr version 9.1
frr defaults datacenter
hostname worker1
log syslog informational
!
interface lo
 ip address 10.255.0.4/32
 ip address 10.244.1.0/24
!
interface eth1
 ip address 10.0.1.1/31
 description to-tor1
!
router bgp 65100
 bgp router-id 10.255.0.4
 !
 neighbor 10.0.1.0 remote-as 65001
 neighbor 10.0.1.0 description tor1
 !
 address-family ipv4 unicast
  network 10.255.0.4/32
  network 10.244.1.0/24
  neighbor 10.0.1.0 activate
 exit-address-family
!
line vty
!
