frr version 9.1
frr defaults datacenter
hostname external
log syslog informational
!
interface lo
 ip address 192.168.100.2/32
!
interface eth0
 ip address 192.168.100.2/24
 description to-spine1
!
router bgp 65200
 bgp router-id 192.168.100.2
 !
 neighbor 192.168.100.1 remote-as 65000
 neighbor 192.168.100.1 description spine1
 !
 address-family ipv4 unicast
  network 192.168.100.0/24
  neighbor 192.168.100.1 activate
 exit-address-family
!
line vty
!
